Add file reset_testnet/bin/run.mjs

diff --git a/cloudflare-job-fair/module-topjob-hx-agent/lib/module-topjob-hx-definition/reset_testnet/bin/job b/cloudflare-job-fair/module-topjob-hx-agent/lib/module-topjob-hx-definition/reset_testnet/bin/job
--- a/cloudflare-job-fair/module-topjob-hx-agent/lib/module-topjob-hx-definition/reset_testnet/bin/job
+++ b/cloudflare-job-fair/module-topjob-hx-agent/lib/module-topjob-hx-definition/reset_testnet/bin/job
@@ -1,11 +1,33 @@
 #!/bin/bash
 
+help () { # {{{1
+  local error=$?
+  local red=$(git config --get-color color.diff.whitespace "red")
+  local reset=$(git config --get-color "" "reset")
+  echo -n "${red}"
+	echo -e "ERROR $error\n\tRequired argument is amountHEXA - a string representing initial amount of HEXA issued to hx Agent by hx Issuer. Usage example:\n\n\t$0 '10000'\n"
+  echo -n "${reset}"
+}
+
 log () { # {{{1
   local blue=$(git config --get-color color.diff.whitespace "blue")
   local reset=$(git config --get-color "" "reset")
   echo "${blue}$@${reset}"
 }
 
+run () { # {{{1
+	log "run $# $@"
+  bin/run.mjs $@
+}
+
+validate () { # {{{1
+	log "$USER validate $# $@"
+  if [ $# -ne 1 ]; then
+    return 1
+  fi
+  return 0
+}
+
 log "$0 started for $USER@$HOSTNAME on $(date) in $PWD" # {{{1
-#validate $@ && run $@ || help $@
+validate $@ && run $@ || help $@
 log "$0 DONE for $USER@$HOSTNAME"
